spring:
  profiles:
    active: native
  cloud:
    config:
      uri: http://locahost:8888
      name: application-zuul
      profile: dev
#      label:
  boot:
    admin:
      client:
        url: http://localhost:9004