server:
  port: 9001

spring:
  application:
    name: cloud-admin
  zipkin:
    base-url: http://localhost:9411

    boot:
      admin:
        client:
          url: http://localhost:9004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

