server:
  port: 9003

spring:
  application:
    name: cloud-zuul
  zipkin:
    base-url: http://localhost:9411

  boot:
    admin:
      client:
        url: http://localhost:9004


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    cloud-admin:
      path: /api/admin/**
      serviceId: cloud-admin
    cloud-auth:
      path: /api/auth/**
      serviceId: cloud-auth